#!/usr/bin/python3
import os
import sys
from enum import Enum

from isa import Opcode


class Signal(str, Enum):
    """Управляющие сигналы процессора."""

    SIGNIF = "signif"  # метка, что это команда ветвления

    LPC = "lpc"  # Загрузка PC
    MUXPC = "muxpc"  # Выбор источника для PC
    LCR = "lcr"  # Загрузка CR (регистра команд)
    LIR = "lir"  # Загрузка IR (регистра инструкций)
    LBR = "lbr"  # Загрузка BR (регистра ветвления)

    MUXALU = "muxalu"  # Выбор источника для ALU (2 бита)
    ALU = "alu"  # Операция ALU (4 бита)
    LDR = "ldr"  # Загрузка DR (регистра данных)
    LAC = "lac"  # Загрузка AC (аккумулятора)

    MUXRSP = "muxrsp"  # Выбор источника для RSP
    MUXDSP = "muxdsp"  # Выбор источника для DSP
    LRSP = "lrsp"  # Загрузка RSP (указателя стека)
    LDSP = "ldsp"  # Загрузка DSP (указателя стека)
    MUXAR = "muxar"  # Выбор источника для AR
    LAR = "lar"  # Загрузка AR (регистра адреса)
    OE = "oe"  # Разрешение чтения из памяти
    WR = "wr"  # Разрешение записи в память

    MPC = "mpc"  # Загрузка MPC (счетчика микрокоманд)
    MUXMPC = "muxmpc"  # Выбор источника для MPC (2 бита)

    def __str__(self):
        """Возвращает строковое значение сигнала."""
        return str(self.value)


microcode = {
    Opcode.LOAD_IMM: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 1,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 2,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.LOAD: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 1,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 3,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.CALL: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 1,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 1,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 1,
            Signal.LAR: 1,
            Signal.MUXRSP: 1,
            Signal.LRSP: 1,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.RETURN: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 1,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 1,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 1,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.SAVE: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 3,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.PLUS: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 1,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.MINUS: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 2,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.MULT: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 3,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.DIV: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 4,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.MOD: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 5,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.AND: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 6,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.OR: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 7,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.NOT: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 8,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.EQUAL: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 9,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.LESS: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 10,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.GREATER: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 11,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 1,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.POP_AC: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 1,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 1,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 3,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 1,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.POP_DR: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 2,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 1,
            Signal.LDSP: 1,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 2,
            Signal.LAR: 1,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 1,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 3,
            Signal.ALU: 0,
            Signal.LDR: 1,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.IF: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 1,
            Signal.LPC: 1,
            Signal.MUXPC: 1,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.ELSE: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.WHILE: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 1,
            Signal.LPC: 1,
            Signal.MUXPC: 1,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.REPEAT: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 1,
            Signal.LIR: 0,
            Signal.LBR: 1,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 1,
        },
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 1,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 1,
            Signal.MUXMPC: 0,
        },
    ],
    Opcode.HALT: [
        {
            Signal.SIGNIF: 0,
            Signal.LPC: 0,
            Signal.MUXPC: 0,
            Signal.LCR: 0,
            Signal.LIR: 0,
            Signal.LBR: 0,
            Signal.MUXALU: 0,
            Signal.ALU: 0,
            Signal.LDR: 0,
            Signal.LAC: 0,
            Signal.MUXAR: 0,
            Signal.LAR: 0,
            Signal.MUXRSP: 0,
            Signal.LRSP: 0,
            Signal.MUXDSP: 0,
            Signal.LDSP: 0,
            Signal.OE: 0,
            Signal.WR: 0,
            Signal.MPC: 0,
            Signal.MUXMPC: 0,
        },
    ],
}


SIGNAL_ORDER = [
    Signal.SIGNIF,
    Signal.LPC,
    Signal.MUXPC,
    Signal.LCR,
    Signal.LIR,
    Signal.LBR,
    Signal.MUXALU,
    Signal.ALU,
    Signal.LDR,
    Signal.LAC,
    Signal.MUXAR,
    Signal.LAR,
    Signal.MUXRSP,
    Signal.LRSP,
    Signal.MUXDSP,
    Signal.LDSP,
    Signal.OE,
    Signal.WR,
    Signal.MPC,
    Signal.MUXMPC,
]

INSTRUCTION_ORDER = [
    Opcode.LOAD_IMM,
    Opcode.LOAD,
    Opcode.CALL,
    Opcode.RETURN,
    Opcode.SAVE,
    Opcode.PLUS,
    Opcode.MINUS,
    Opcode.MULT,
    Opcode.DIV,
    Opcode.MOD,
    Opcode.AND,
    Opcode.OR,
    Opcode.NOT,
    Opcode.EQUAL,
    Opcode.LESS,
    Opcode.GREATER,
    Opcode.POP_AC,
    Opcode.POP_DR,
    Opcode.IF,
    Opcode.ELSE,
    Opcode.WHILE,
    Opcode.REPEAT,
    Opcode.HALT,
]


linking_table = {
    Opcode.LOAD_IMM: 4,
    Opcode.LOAD: 8,
    Opcode.CALL: 16,
    Opcode.RETURN: 24,
    Opcode.SAVE: 40,
    Opcode.PLUS: 44,
    Opcode.MINUS: 48,
    Opcode.MULT: 52,
    Opcode.DIV: 56,
    Opcode.MOD: 60,
    Opcode.AND: 64,
    Opcode.OR: 68,
    Opcode.NOT: 72,
    Opcode.EQUAL: 76,
    Opcode.LESS: 80,
    Opcode.GREATER: 84,
    Opcode.POP_AC: 88,
    Opcode.POP_DR: 100,
    Opcode.IF: 112,
    Opcode.ELSE: 120,
    Opcode.WHILE: 128,
    Opcode.REPEAT: 136,
    Opcode.HALT: 144,
}


def encode_microinstruction(step: dict) -> int:
    """
    Кодирует один шаг микрокода в 26-битное целое число.
    muxalu — 2 бита, alu — 4 бита, muxmpc - 2 бита, muxar - 2 бита остальные сигналы 1 бит
    """
    bitstr = ""
    for name in SIGNAL_ORDER:
        val = step.get(name, 0)
        if (name == Signal.MUXALU) or (name == Signal.MUXMPC) or (name == Signal.MUXAR) or (name == Signal.MUXPC):
            bitstr += f"{val:02b}"
        elif name == Signal.ALU:
            bitstr += f"{val:04b}"
        else:
            bitstr += f"{val:01b}"
    print(bitstr)
    return int(bitstr, 2)


# попозже добавить автоматическое создание таблицы линковки
def save_to_bin(microcode: dict, filename: str):
    global linking_table
    os.makedirs(os.path.dirname(os.path.abspath(filename)) or ".", exist_ok=True)
    choose_op_instr = "011111000000000000000000110"
    steps = [int(choose_op_instr, 2)]
    address = 4
    for opcode in INSTRUCTION_ORDER:
        # Проверяем тип значения - список или словарь
        print(opcode, address)
        op_steps = microcode[opcode]
        for step in op_steps:
            encoded = encode_microinstruction(step)
            steps.append(encoded)
            address += 4

    binary_bytes = bytearray()

    with open(filename, "wb") as f:
        for code in steps:
            # Сохраняем как 4 байта (24 бита)
            binary_bytes.extend(code.to_bytes(4, byteorder="big"))
        f.write(bytes(binary_bytes))

    print(f"Saved {len(steps)} microinstructions to {filename}")


def microcode_from_byte(target):
    # одна инструкция 4 байта
    with open(target, "rb") as f:
        byte_array = list(f.read())
    return byte_array  # noqa: RET504


if __name__ == "__main__":
    assert len(sys.argv) == 2, "Wrong arguments: translator.py <input_file> <target_file>"
    _, target = sys.argv
    save_to_bin(microcode, target)

# уже в глазах двоится, проверю правильность заполнения позже
# одна микроинструкция - 24 бита, значит mpc увеличивается на 3 каждый раз
# также нужно добавить нулевую инструкцию - цикл выборки команды
